name: Landing Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Landing Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Deploying Landing - latest commit
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: ./new-landing.sh